openapi: 3.0.0
info:
  title: API Loja Virtual
  version: 0.0.1
tags:
  - produtos
paths:
  /produtos:
    post:
      requestBody:
        content:
          application-json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          content:
            application-json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          content:
            application-json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components: 
  schemas:
    Produto:
      type: object
      properties:
        nome:
          type: string
        preco:
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string